#!/usr/bin/env bash
set -euo pipefail

# ===========================================
# Moodle Host Nginx Setup Script
# ===========================================
# This script sets up nginx on the host server to proxy
# requests to the Moodle Docker container with SSL via Certbot

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

# Load configuration from .env file
if [ -f "$SCRIPT_DIR/.env" ]; then
    source "$SCRIPT_DIR/.env"
else
    echo "Error: .env file not found. Please copy .env.example to .env and configure it."
    exit 1
fi

# Validate required variables
if [ -z "${DOMAIN:-}" ] || [ "$DOMAIN" = "moodle.example.com" ]; then
    echo "Error: Please set a valid DOMAIN in .env file"
    exit 1
fi

if [ -z "${CERTBOT_EMAIL:-}" ] || [ "$CERTBOT_EMAIL" = "admin@example.com" ]; then
    echo "Error: Please set a valid CERTBOT_EMAIL in .env file"
    exit 1
fi

MOODLE_PORT="${MOODLE_PORT:-8080}"

echo "=========================================="
echo "  Moodle Host Nginx Setup"
echo "=========================================="
echo "Domain: $DOMAIN"
echo "Moodle Port: $MOODLE_PORT"
echo "Certbot Email: $CERTBOT_EMAIL"
echo "=========================================="
echo ""

# --- Check if running as root or with sudo ---
if [ "$EUID" -ne 0 ]; then
    echo "Please run this script with sudo or as root"
    exit 1
fi

# --- Install nginx & certbot if not present ---
echo "[STEP] Installing nginx and certbot..."
apt update
apt install -y nginx certbot python3-certbot-nginx

# --- Check if config already exists ---
if [ -f "/etc/nginx/sites-available/$DOMAIN" ]; then
    echo "[WARN] Nginx config for $DOMAIN already exists."
    read -p "Do you want to overwrite it? (y/n) " -n 1 -r
    echo
    if [[ ! $REPLY =~ ^[Yy]$ ]]; then
        echo "Keeping existing configuration."
        exit 0
    fi
fi

# --- Write nginx config for reverse proxy ---
echo "[STEP] Creating nginx configuration..."
cat <<EOF > /etc/nginx/sites-available/$DOMAIN
# Moodle reverse proxy configuration
# Generated by moodle-docker-prod setup script

server {
    listen 80;
    listen [::]:80;
    server_name $DOMAIN;

    # Increase client body size for file uploads
    client_max_body_size 256M;

    location / {
        proxy_pass http://127.0.0.1:$MOODLE_PORT;
        proxy_http_version 1.1;
        proxy_set_header Host \$host;
        proxy_set_header X-Real-IP \$remote_addr;
        proxy_set_header X-Forwarded-For \$proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto \$scheme;
        proxy_set_header X-Forwarded-Host \$host;
        proxy_set_header X-Forwarded-Port \$server_port;
        
        # Websocket support (if needed)
        proxy_set_header Upgrade \$http_upgrade;
        proxy_set_header Connection "upgrade";
        
        # Timeouts
        proxy_connect_timeout 300;
        proxy_send_timeout 300;
        proxy_read_timeout 300;
        send_timeout 300;
        
        # Buffering
        proxy_buffering on;
        proxy_buffer_size 128k;
        proxy_buffers 256 16k;
        proxy_busy_buffers_size 256k;
    }
}
EOF

# --- Enable site ---
echo "[STEP] Enabling site..."
ln -sf /etc/nginx/sites-available/$DOMAIN /etc/nginx/sites-enabled/

# --- Test nginx config ---
echo "[STEP] Testing nginx configuration..."
nginx -t

# --- Restart nginx ---
echo "[STEP] Restarting nginx..."
systemctl restart nginx

# --- Run certbot for SSL ---
echo "[STEP] Obtaining SSL certificate..."
certbot --nginx -d $DOMAIN \
    --non-interactive --agree-tos --email $CERTBOT_EMAIL --redirect

echo ""
echo "=========================================="
echo "  Setup Complete!"
echo "=========================================="
echo ""
echo "Your Moodle site is now available at: https://$DOMAIN"
echo ""
echo "Make sure the Moodle Docker containers are running:"
echo "  cd $SCRIPT_DIR && docker compose up -d"
echo ""
echo "SSL certificate will auto-renew via certbot timer."
echo ""